# Generated by Django 4.0.5 on 2022-07-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Rut'),
        ),
    ]
